"""add

Revision ID: 92d8bcb1e372
Revises: 490bf68af06e
Create Date: 2025-11-26 21:01:49.154150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d8bcb1e372'
down_revision: Union[str, Sequence[str], None] = '490bf68af06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=1024), nullable=True))
    op.add_column('categories', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'photo')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
